polls/urls.py
from django.urls import path

from . import views

#para poder usar el reverso es necesario
app_name="polls"

urlpatterns=[
    path("",views.IndexView.as_view(),name="index"),


    #ex: /polls/5/
    #si lo quieo trabajar todo como clase tambien cambiar <int:pk>
    path("<int:question_id>/",views.detail,name="details"),
    path("<int:question_id>/results/",views.results,name="results"),
    path("<int:question_id>/vote/",views.vote,name="vote"),

]

premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/",include("polls.urls"))
]

polls/models.py
from django.db import models


from django.utils import timezone
import datetime
# Create your models here.

#Nombre del modelo en singular siempre
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)




class Choice(models.Model):
    #relacion de uno a muchos 
    #models.CASCADE es cuando se borre una pregunta se borrara  sun opciones tambien...
    #choice opcion
    question = models.ForeignKey(Question , on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)#los votos van en 0 pues asi se le esta inicializando

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render , get_object_or_404
from .models import Choice

from django.http import HttpResponse , HttpResponseRedirect

from django.urls import reverse

#vamos a importar el modelo
from .models import Question

#vistas basadas en clases
from django.views import generic 





# Create your views here.

""" 


def index(request):
    latest_question_list= Question.objects.all()
    #Con el render yo le estoy pasando al template el el diccionarioo con los datos 
    #que hay en la variable latest_question_list
    return render(
        request,
        "polls/index.html",
        {"latest_question_list":latest_question_list}
        )
"""

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]#- pues ordena desde las mas nuevas hasta las mas viejas





def detail(request,question_id):
    #si encuenrta la question_id lo almacena en pk en caso contrario lanza el error 404
    question=get_object_or_404(Question,pk=question_id)
    return render(
        request,
        "polls/detail.html",
        {"question":question} 
        )



""" 
class DetailView(generic.DetailView):
   model=Question
   template_name="polls/detail.html"

class ResultsView(generic.DetailView):
   model=Question
   template_name="polls/results.html"

"""


def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(
        request,
        "polls/results.html",
        {"question":question}
    )
    #return HttpResponse(f"Estas viendo los resultados de la pregunta numero {question_id}")



def vote(request,question_id):
    #nos va llegar el name y id de la respuesta elegida


    question = get_object_or_404(Question , pk=question_id) 
    #pues vamos a intentar obtener la respuesta del usuario
    try : 
        #vamos a usar el request pues eso es lo ques estamos recibiendo del post
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError ,  Choice.DoesNotExist):
       return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message":"No elegiste una respuesta"
            }
        )
    else:
        selected_choice.votes +=1
        selected_choice.save()
        #con el HttpResponseRedirect me aseguro que el usuario no envie dos veces el formulario 
        #                                    "app_name:name"  args son los argumentos de la url que esta en url en este caso la question.id 

        return HttpResponseRedirect(reverse("polls:results" , args=[(question.id)]))



    #question = Question.objects.get(pk=question_id) 

   

  

polls/templates/polls/detail.html
<!--
Ahora sabemos que cada vez que una persona envie el formulario 
se va ejecutar la vista que esta en el action 

se usa el metodo post para que los datos viajen oculto
ahora django nos va redirigir a la vista vote y le pasa como parametro question.id
-->
<form action="{% url 'polls:vote' question.id  %}"  method="post">
{% csrf_token %} 
<fieldset>
    <legend> <h1>{{question.question_text}} </h1></legend>

    
    {% if error_message %}
        <p><strong>{{ error_message}}</strong></p>
    {% endif %}


    {% for choice in question.choice_set.all %}
   
        <input 
        type="radio"
        name="choice"
        id="choice{{forloop.counter}}"
        value="{{choice.id}}"
        
        >
        <label for="choice{{forloop.counter}}">
            {{ choice.choice_text }}
        </label>

      
        <br>

    
    {% endfor %}
        

</fieldset>

<input type="submit" value="Votar">
</form>


<!-- 
<h1> {{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
    {% endfor %}
</ul>

-->

polls/templates/polls/index.html
{% if  latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <!-- Para no hacer hard coding-->
            
       <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}} </a></li>
   
        {% endfor %}
    </ul>


{% else %}

    <p>No polls are available</p>

{% endif %}
    

polls/templates/polls/results.html
<h1>{{question.question_text}} </h1>

<ul>
    {% for choice in  question.choice_set.all %}
        <li>{{choice.choice_text}} --  {{choice.votes}}  vote{{choice.votes|pluralize}}</li>
      
    {% endfor %}
</ul>


<a href="{% url 'polls:details' question.id %}">¿Te gustaria votar de nuevo?</a>